### ISSUE TITLE
agent启动失败

### ISSUE THREAD

**Issue by crazy0x70** [akile-network/akile_monitor#16]
× ak_client.service - AkileCloud Monitor Service
     Loaded: loaded (/etc/systemd/system/ak_client.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-12-05 03:38:04 UTC; 8s ago
   Duration: 75ms
    Process: 1003357 ExecStart=/etc/ak_monitor/client (code=exited, status=1/FAILURE)
   Main PID: 1003357 (code=exited, status=1/FAILURE)
        CPU: 46ms

Dec 05 03:38:02 Lsky-Pro systemd[1]: ak_client.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 03:38:02 Lsky-Pro systemd[1]: ak_client.service: Failed with result 'exit-code'.
Dec 05 03:38:04 Lsky-Pro systemd[1]: ak_client.service: Scheduled restart job, restart counter is at 5.
Dec 05 03:38:04 Lsky-Pro systemd[1]: Stopped ak_client.service - AkileCloud Monitor Service.
Dec 05 03:38:04 Lsky-Pro systemd[1]: ak_client.service: Start request repeated too quickly.
Dec 05 03:38:04 Lsky-Pro systemd[1]: ak_client.service: Failed with result 'exit-code'.
Dec 05 03:38:04 Lsky-Pro systemd[1]: Failed to start ak_client.service - AkileCloud Monitor Service.
root@Lsky-Pro:/etc/ak_monitor# sudo journalctl -u ak_client.service -b
Dec 05 02:56:43 Lsky-Pro systemd[1]: Started ak_client.service - AkileCloud Monitor Service.
Dec 05 02:56:43 Lsky-Pro client[961029]: 2024/12/05 02:56:43 invalid character '\n' in string literal
Dec 05 02:56:43 Lsky-Pro client[961029]: panic: invalid character '\n' in string literal
Dec 05 02:56:43 Lsky-Pro client[961029]: goroutine 1 [running]:
Dec 05 02:56:43 Lsky-Pro client[961029]: log.Panic({0xc000093bd8?, 0x122?, 0x200?})
Dec 05 02:56:43 Lsky-Pro client[961029]:         /usr/local/opt/go/libexec/src/log/log.go:432 +0x5a
Dec 05 02:56:43 Lsky-Pro client[961029]: main.LoadConfig()
Dec 05 02:56:43 Lsky-Pro client[961029]:         /Users/mzfqy/项目/golang/akile_monitor/client/config.go:26 +0xdf
Dec 05 02:56:43 Lsky-Pro client[961029]: main.main()
Dec 05 02:56:43 Lsky-Pro client[961029]:         /Users/mzfqy/项目/golang/akile_monitor/client/main.go:19 +0x25
Dec 05 02:56:43 Lsky-Pro systemd[1]: ak_client.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 05 02:56:43 Lsky-Pro systemd[1]: ak_client.service: Failed with result 'exit-code'.
Dec 05 02:56:53 Lsky-Pro systemd[1]: ak_client.service: Scheduled restart job, restart counter is at 1.
Dec 05 02:56:53 Lsky-Pro systemd[1]: Stopped ak_client.service - AkileCloud Monitor Service.
Dec 05 02:56:53 Lsky-Pro systemd[1]: Started ak_client.service - AkileCloud Monitor Service.
Dec 05 02:56:53 Lsky-Pro client[961040]: 2024/12/05 02:56:53 invalid character '\n' in string literal
Dec 05 02:56:53 Lsky-Pro client[961040]: panic: invalid character '\n' in string literal
Dec 05 02:56:53 Lsky-Pro client[961040]: goroutine 1 [running]:
Dec 05 02:56:53 Lsky-Pro client[961040]: log.Panic({0xc000093bd8?, 0x122?, 0x200?})
Dec 05 02:56:53 Lsky-Pro client[961040]:         /usr/local/opt/go/libexec/src/log/log.go:432 +0x5a
Dec 05 02:56:53 Lsky-Pro client[961040]: main.LoadConfig()
Dec 05 02:56:53 Lsky-Pro client[961040]:         /Users/mzfqy/项目/golang/akile_monitor/client/config.go:26 +0xdf
Dec 05 02:56:53 Lsky-Pro client[961040]: main.main()
Dec 05 02:56:53 Lsky-Pro client[961040]:         /Users/mzfqy/项目/golang/akile_monitor/client/main.go:19 +0x25
Dec 05 02:56:53 Lsky-Pro systemd[1]: ak_client.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 05 02:56:53 Lsky-Pro systemd[1]: ak_client.service: Failed with result 'exit-code'.
Dec 05 02:56:56 Lsky-Pro systemd[1]: Stopped ak_client.service - AkileCloud Monitor Service.
Dec 05 02:58:02 Lsky-Pro systemd[1]: Started ak_client.service - AkileCloud Monitor Service.
Dec 05 02:58:02 Lsky-Pro client[961208]: 2024/12/05 02:58:02 invalid character '\n' in string literal

**Comment by Venompool888** [comment]
问题就是这个 https://github.com/akile-network/akile_monitor/issues/15

**Comment by crazy0x70** [comment]
> 问题就是这个 #15

 我ifconfig查看网口是eth0，修改"net_name": "eth0"后还是这样
